import {
  ActionPoint,
  DashboardStats,
  FollowUp,
  Returnee,
} from "../definitions/type";

export const mockReturnees: Returnee[] = [
  {
    id: "1",
    registrationId: "RMIS-2024-00001",
    firstName: "Binod",
    lastName: "Gurung",
    dateOfBirth: "1990-05-15",
    gender: "male",
    phone: "+977-9841234567",
    passportNumber: "NP12345678",
    address: {
      province: "Bagmati",
      district: "Kathmandu",
      municipality: "Kathmandu Metropolitan City",
      ward: "10",
    },
    migrationHistory: {
      destinationCountry: "Qatar",
      departureDate: "2020-03-15",
      returnDate: "2024-01-10",
      reasonForReturn: "Contract ended",
    },
    consent: {
      given: true,
      date: "2024-01-15",
    },
    status: "follow_up",
    vulnerabilityLevel: "medium",
    assignedCounselorId: "3",
    createdById: "2",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    registrationId: "RMIS-2024-00002",
    firstName: "Maya",
    lastName: "Tamang",
    dateOfBirth: "1995-08-22",
    gender: "female",
    phone: "+977-9851234568",
    passportNumber: "NP87654321",
    address: {
      province: "Gandaki",
      district: "Kaski",
      municipality: "Pokhara Metropolitan City",
      ward: "5",
    },
    migrationHistory: {
      destinationCountry: "UAE",
      departureDate: "2019-06-20",
      returnDate: "2024-02-05",
      reasonForReturn: "Health issues",
    },
    consent: {
      given: true,
      date: "2024-02-08",
    },
    status: "assessment",
    vulnerabilityLevel: "high",
    assignedCounselorId: "3",
    createdById: "2",
    createdAt: new Date("2024-02-08"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "3",
    registrationId: "RMIS-2024-00003",
    firstName: "Ramesh",
    lastName: "Adhikari",
    dateOfBirth: "1988-12-01",
    gender: "male",
    phone: "+977-9861234569",
    address: {
      province: "Province 1",
      district: "Jhapa",
      municipality: "Birtamod Municipality",
      ward: "3",
    },
    migrationHistory: {
      destinationCountry: "Malaysia",
      departureDate: "2018-09-10",
      returnDate: "2024-02-15",
      reasonForReturn: "Family emergency",
    },
    consent: {
      given: true,
      date: "2024-02-18",
    },
    status: "registered",
    createdById: "2",
    createdAt: new Date("2024-02-18"),
    updatedAt: new Date("2024-02-18"),
  },
  {
    id: "4",
    registrationId: "RMIS-2024-00004",
    firstName: "Sushila",
    lastName: "Rai",
    dateOfBirth: "1992-03-25",
    gender: "female",
    phone: "+977-9871234570",
    passportNumber: "NP11223344",
    address: {
      province: "Province 1",
      district: "Sunsari",
      municipality: "Inaruwa Municipality",
      ward: "7",
    },
    migrationHistory: {
      destinationCountry: "Saudi Arabia",
      departureDate: "2017-11-05",
      returnDate: "2024-01-25",
      reasonForReturn: "Deportation",
    },
    consent: {
      given: true,
      date: "2024-01-28",
    },
    status: "action_planning",
    vulnerabilityLevel: "high",
    assignedCounselorId: "3",
    createdById: "2",
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "5",
    registrationId: "RMIS-2024-00005",
    firstName: "Kumar",
    lastName: "Shrestha",
    dateOfBirth: "1985-07-18",
    gender: "male",
    phone: "+977-9881234571",
    address: {
      province: "Bagmati",
      district: "Lalitpur",
      municipality: "Lalitpur Metropolitan City",
      ward: "12",
    },
    migrationHistory: {
      destinationCountry: "South Korea",
      departureDate: "2021-02-14",
      returnDate: "2024-02-20",
      reasonForReturn: "Visa expired",
    },
    consent: {
      given: true,
      date: "2024-02-22",
    },
    status: "closed",
    vulnerabilityLevel: "low",
    createdById: "2",
    createdAt: new Date("2024-02-22"),
    updatedAt: new Date("2024-03-01"),
  },
];

export const mockActionPoints: ActionPoint[] = [
  {
    id: "1",
    returneeId: "1",
    type: "Skill Training",
    description: "Enroll in vocational training program for returnees",
    dueDate: "2024-03-15",
    status: "in_progress",
    referralOrganization: "CTEVT",
    createdById: "3",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    returneeId: "2",
    type: "Medical Support",
    description: "Arrange medical checkup and follow-up treatment",
    dueDate: "2024-02-28",
    status: "pending",
    referralOrganization: "Bir Hospital",
    createdById: "3",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "3",
    returneeId: "4",
    type: "Legal Aid",
    description: "Connect with legal support for wage recovery claim",
    dueDate: "2024-03-10",
    status: "pending",
    referralOrganization: "NHRC",
    createdById: "3",
    createdAt: new Date("2024-02-01"),
  },
];

export const mockFollowUps: FollowUp[] = [
  {
    id: "1",
    actionPointId: "1",
    notes: "Initial enrollment completed. Training starts next week.",
    nextFollowUpDate: "2024-02-25",
    status: "completed",
    createdAt: new Date("2024-02-01"),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalRegistered: 156,
  activeCases: 89,
  closedCases: 67,
  overdueFollowUps: 12,
  vulnerabilityBreakdown: {
    non: 45,
    low: 38,
    medium: 52,
    high: 21,
  },
};

export const provinces = [
  "Province 1",
  "Madhesh",
  "Bagmati",
  "Gandaki",
  "Lumbini",
  "Karnali",
  "Sudurpashchim",
];

export const destinationCountries = [
  "Qatar",
  "UAE",
  "Saudi Arabia",
  "Malaysia",
  "South Korea",
  "Japan",
  "Kuwait",
  "Bahrain",
  "Oman",
  "Other",
];

export const returnReasons = [
  "Contract ended",
  "Health issues",
  "Family emergency",
  "Deportation",
  "Visa expired",
  "Voluntary return",
  "Other",
];
